{{- if .Values.controller.baseConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "runway.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "runway.labels" . | nindent 4 }}
data:
  base-config.yaml: |
    {{- .Values.controller.baseConfig | nindent 4 }}
{{- end }}
