{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "runway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "runway.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "runway.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: {{ .Values.ports.http }}
          protocol: TCP
        - port: {{ .Values.ports.https }}
          protocol: TCP
        - port: {{ .Values.ports.metrics }}
          protocol: TCP
{{- end }}
