{{- if .Values.priorityClass.create }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "runway.fullname" . }}
  labels:
    {{- include "runway.labels" . | nindent 4 }}
value: {{ .Values.priorityClass.value }}
globalDefault: false
description: "Priority class for the API Gateway ingress controller"
{{- end }}
