apiVersion: v1
kind: Service
metadata:
  name: {{ include "runway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "runway.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.ports.http }}
      targetPort: http
      protocol: TCP
    - name: https
      port: {{ .Values.ports.https }}
      targetPort: https
      protocol: TCP
  selector:
    {{- include "runway.selectorLabels" . | nindent 4 }}
