global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "runway"
    static_configs:
      - targets: ["runway:8081"]
    metrics_path: "/metrics"
    scrape_interval: 5s
