global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:8081"]
    metrics_path: "/metrics"
    scrape_interval: 5s
