{{- if .Values.ingressClass.create }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.controller.ingressClass }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  {{- if .Values.ingressClass.default }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
  {{- end }}
spec:
  controller: {{ .Values.controller.controllerName }}
{{- end }}
